version: '3.1'

services:

  db:
    container_name: my_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./tmp/data_stage:/var/lib/posgresql/data
    ports: 
      - ${DB_PORT}:${DB_PORT}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  app:
    image: node:16.13.1
    working_dir: /app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/app
    command: sh -c "npx nodemon -L -r dotenv/config src/app.js"